---
- name: Google Drive | Add Repository
  tags: [extras,packages,google-drive]
  apt_repository:
    repo: ppa:alessandro-strada/ppa
    codename: xenial
- name: Google Drive | Install package
  tags: [extras,packages,google-drive]
  package:
    name: google-drive-ocamlfuse
    state: latest
    update_cache: yes
