---
- name: TLP Power Management | Add Repository
  tags: [yoga,system,tlp]
  apt_repository:
    repo: ppa:linrunner/tlp
    codename: xenial
- name: TLP Power Management | Add Proposed Repository For acpi-call Hotfixes
  tags: [yoga,system,tlp]
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu/ xenial-proposed restricted main multiverse universe'
    filename: official-package-repositories
    state: present
- name: TLP Power Management | Install Packages
  tags: [yoga,system,tlp]
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - acpi-call
    - tlp
    - tlp-rdw
- name: TLP Power Management | Remove Proposed Repository
  tags: [yoga,system,tlp]
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu/ xenial-proposed restricted main multiverse universe'
    filename: official-package-repositories
    state: absent
    update_cache: yes
- name: TLP Power Management | Tweak Configuration
  tags: [yoga,system,tlp]
  lineinfile:
    path: /etc/default/tlp
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: 'MAX_LOST_WORK_SECS_ON_BAT', value: '90' }
    - { key: 'START_CHARGE_THRESH_BAT0', value: '70' }
    - { key: 'STOP_CHARGE_THRESH_BAT0', value: '80' }
    - { key: 'RESTORE_THRESHOLDS_ON_BAT', value: '1' }
